name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      # - run: pnpm dlx nx-cloud start-ci-run --distribute-on="3 linux-medium-js" --stop-agents-after="e2e-ci"

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm exec playwright install --with-deps
      - uses: nrwl/nx-set-shas@v4
        with:
          main-branch-name: main
          set-environment-variables-for-job: true
          error-on-no-successful-workflow: false
          last-successful-event: push

      - name: Debug nx-set-shas
        run: |
          echo "Branch: ${{ github.ref }}"
          echo "Event: ${{ github.event_name }}"
          echo "SHA: ${{ github.sha }}"

      - name: Run E2E Tests
        run: |
          nx serve server --configuration=ci & # Inicia o servidor em background
          SERVER_PID=$! # Captura o PID do servidor
          sleep 10 # Espera inicialização básica
          npx wait-on http://127.0.0.1:3000/api --timeout 60000 # Espera até 60s
          nx e2e server-e2e --configuration=ci
          kill $SERVER_PID # Encerra o servidor após os testes

      # Prepend any command with "nx-cloud record --" to record its logs to Nx Cloud
      # - run: pnpm exec nx-cloud record -- echo Hello World
      # Nx Affected runs only tasks affected by the changes in this PR/commit. Learn more: https://nx.dev/ci/features/affected
      # When you enable task distribution, run the e2e-ci task instead of e2e
      - run: pnpm exec nx affected -t lint test build e2e
